apiVersion: v1
kind: Secret
metadata:
  name: mysql-wordpress-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  mysql-database: d29yZHByZXNz  # wordpress
  mysql-user: d29yZHByZXNzdXNlcg==  # wordpressuser
  mysql-password: d29yZHByZXNzcGFzcw==  # wordpresspass
  wordpress-auth-key: YXV0aGtleXNlY3JldA==  # authkeysecret
  wordpress-secure-auth-key: c2VjdXJlYXV0aGtleQ==  # secureauthkey
  wordpress-logged-in-key: bG9nZ2VkaW5rZXk=  # loggedinkey
  wordpress-nonce-key: bm9uY2VrZXk=  # noncekey