apiVersion: v1
kind: Service
metadata: 
  name: helloworld-service
spec:
   ports: 
      - port: 80
        nodePort: 30001
        targetPort: 80
        protocol: TCP
   selector:
       app: vproapp
   type: LoadBalancer
