---
apiVersion: v1
kind: Pod
metadata:
  name: vproapp1
  labels:
     app: vproapp
spec:
  containers:
    - name: appcontainer
      image: nginx:stable-perl
      ports:
        - name: vproapp-port
          containerPort: 80

