apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "wordpress-chart.fullname" . }}-mysql'
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
{{- include "wordpress-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mysql
{{- include "wordpress-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: '{{ include "wordpress-chart.fullname" . }}-secret'
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: '{{ include "wordpress-chart.fullname" . }}-secret'
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: '{{ include "wordpress-chart.fullname" . }}-secret'
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: '{{ include "wordpress-chart.fullname" . }}-secret'
              key: mysql-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: '{{ include "wordpress-chart.fullname" . }}-mysql-pvc'