apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-mysql-pvc
  labels:
{{ include "wordpress-chart.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.mysql.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-wordpress-pvc
  labels:
{{ include "wordpress-chart.labels" . | indent 4 }}
spec:
  storageClassName: {{ .Values.wordpress.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.storage.size }}