apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-secret
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword }}
  mysql-database: {{ .Values.secrets.mysqlDatabase }}
  mysql-user: {{ .Values.secrets.mysqlUser }}
  mysql-password: {{ .Values.secrets.mysqlPassword }}
  wordpress-auth-key: {{ .Values.secrets.wordpressAuthKey }}
  wordpress-secure-auth-key: {{ .Values.secrets.wordpressSecureAuthKey }}
  wordpress-logged-in-key: {{ .Values.secrets.wordpressLoggedInKey }}
  wordpress-nonce-key: {{ .Values.secrets.wordpressNonceKey }}