apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-wordpress
  labels:
    {{- include "wordpress-chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      {{- include "wordpress-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: wordpress
        {{- include "wordpress-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ include "wordpress-chart.fullname" . }}-mysql-service:3306
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-chart.fullname" . }}-secret
              key: mysql-database
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-chart.fullname" . }}-secret
              key: mysql-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-chart.fullname" . }}-secret
              key: mysql-password
        - name: WORDPRESS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-chart.fullname" . }}-secret
              key: wordpress-auth-key
        - name: WORDPRESS_SECURE_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-chart.fullname" . }}-secret
              key: wordpress-secure-auth-key
        - name: WORDPRESS_LOGGED_IN_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-chart.fullname" . }}-secret
              key: wordpress-logged-in-key
        - name: WORDPRESS_NONCE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress-chart.fullname" . }}-secret
              key: wordpress-nonce-key
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: {{ include "wordpress-chart.fullname" . }}-wordpress-pvc